name: tadamon
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  feedback: ^3.1.0
  google_mlkit_barcode_scanning: ^0.13.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  equatable: 2.0.5
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  font_awesome_flutter: ^10.8.0
  flutter_localization: ^0.2.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  simple_barcode_scanner: ^0.2.3
  firebase_core: ^3.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: ArabicFont
      fonts:
        - asset: assets/fonts/ar/Tajawal-Regular.ttf

flutter_intl:
  enabled: true

