name: tadamon
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  google_mlkit_barcode_scanning: ^0.13.0
  image_picker: ^1.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  flutter_localization: ^0.2.2
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  simple_barcode_scanner: ^0.2.3
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  fluttertoast: ^8.2.10
  connectivity_plus: ^6.1.1
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  intl_utils: ^2.8.8
  hive: ^2.2.3
  path_provider: ^2.0.15
  hive_flutter: ^1.1.0
  syncfusion_flutter_maps: ^28.2.5
  flutter_svg: ^2.0.17
  infinite_scroll_pagination: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1




flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/
    
  fonts:
    - family: ArabicFont
      fonts:
        - asset: assets/fonts/ar/Tajawal-Regular.ttf

flutter_intl:
  enabled: true


