import 'package:flutter/material.dart';

final ThemeData lightTheme = ThemeData(
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xffaa352c),
    surfaceTint: Color(0xffaa352c),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffff7567),
    onPrimaryContainer: Color(0xff310001),
    secondary: Color(0xff8b4d46),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffffb7ae),
    onSecondaryContainer: Color(0xff5c2822),
    tertiary: Color(0xff7a5900),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xffcc9816),
    onTertiaryContainer: Color(0xff1d1300),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff410002),
    surface: Color(0xfffff8f7),
    onSurface: Color(0xff251917),
    onSurfaceVariant: Color(0xff58413e),
    outline: Color(0xff8c716d),
    outlineVariant: Color(0xffdfbfbb),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff3b2d2b),
    inversePrimary: Color(0xffffb4aa),
    primaryFixed: Color(0xffffdad5),
    onPrimaryFixed: Color(0xff410002),
    primaryFixedDim: Color(0xffffb4aa),
    onPrimaryFixedVariant: Color(0xff891c18),
    secondaryFixed: Color(0xffffdad5),
    onSecondaryFixed: Color(0xff380c09),
    secondaryFixedDim: Color(0xffffb4aa),
    onSecondaryFixedVariant: Color(0xff6f3630),
    tertiaryFixed: Color(0xffffdea2),
    onTertiaryFixed: Color(0xff261900),
    tertiaryFixedDim: Color(0xfff6be3f),
    onTertiaryFixedVariant: Color(0xff5c4200),
    surfaceDim: Color(0xffecd5d2),
    surfaceBright: Color(0xfffff8f7),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfffff0ee),
    surfaceContainer: Color(0xffffe9e6),
    surfaceContainerHigh: Color(0xfffae3e0),
    surfaceContainerHighest: Color(0xfff5ddda),
  ),
  fontFamily: 'ArabicFont',
  drawerTheme: const DrawerThemeData(
    backgroundColor: Color(0xfffff8f7),
  ),
  dialogTheme: const DialogThemeData(
    backgroundColor: Color(0xfffff8f7)
  )
);
