// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/products_scanner/data/models/product_object_box_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6072440110067899483),
      name: 'ProductObjectBoxModel',
      lastPropertyId: const obx_int.IdUid(7, 5083381345625000545),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3257500603860786490),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7184596676276845706),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4125859010512694816),
            name: 'serialNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7999642378580237386),
            name: 'manufacture',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1774581651058165040),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6648500980729496271),
            name: 'trusted',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5083381345625000545),
            name: 'onError',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 6072440110067899483),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ProductObjectBoxModel: obx_int.EntityDefinition<ProductObjectBoxModel>(
        model: _entities[0],
        toOneRelations: (ProductObjectBoxModel object) => [],
        toManyRelations: (ProductObjectBoxModel object) => {},
        getId: (ProductObjectBoxModel object) => object.id,
        setId: (ProductObjectBoxModel object, int id) {
          object.id = id;
        },
        objectToFB: (ProductObjectBoxModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final serialNumberOffset = fbb.writeString(object.serialNumber);
          final manufactureOffset = fbb.writeString(object.manufacture);
          final categoryOffset = fbb.writeString(object.category);
          final onErrorOffset = fbb.writeString(object.onError);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, serialNumberOffset);
          fbb.addOffset(3, manufactureOffset);
          fbb.addOffset(4, categoryOffset);
          fbb.addBool(5, object.trusted);
          fbb.addOffset(6, onErrorOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final serialNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final manufactureParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final trustedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final onErrorParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = ProductObjectBoxModel(
              name: nameParam,
              serialNumber: serialNumberParam,
              manufacture: manufactureParam,
              category: categoryParam,
              trusted: trustedParam,
              onError: onErrorParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProductObjectBoxModel] entity fields to define ObjectBox queries.
class ProductObjectBoxModel_ {
  /// See [ProductObjectBoxModel.id].
  static final id = obx.QueryIntegerProperty<ProductObjectBoxModel>(
      _entities[0].properties[0]);

  /// See [ProductObjectBoxModel.name].
  static final name = obx.QueryStringProperty<ProductObjectBoxModel>(
      _entities[0].properties[1]);

  /// See [ProductObjectBoxModel.serialNumber].
  static final serialNumber = obx.QueryStringProperty<ProductObjectBoxModel>(
      _entities[0].properties[2]);

  /// See [ProductObjectBoxModel.manufacture].
  static final manufacture = obx.QueryStringProperty<ProductObjectBoxModel>(
      _entities[0].properties[3]);

  /// See [ProductObjectBoxModel.category].
  static final category = obx.QueryStringProperty<ProductObjectBoxModel>(
      _entities[0].properties[4]);

  /// See [ProductObjectBoxModel.trusted].
  static final trusted = obx.QueryBooleanProperty<ProductObjectBoxModel>(
      _entities[0].properties[5]);

  /// See [ProductObjectBoxModel.onError].
  static final onError = obx.QueryStringProperty<ProductObjectBoxModel>(
      _entities[0].properties[6]);
}
