name: CI
on:
    pull_request:
    push:
        branches:
            - master


jobs:


#  flutter-test:
#    name: Flutter Test and analyze
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '17'
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter analyze
#      - run: flutter test



#build app apk appbundle
  build_apk:
    name: Flutter Build APK For Android
    #needs: [flutter-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle


#build app for IOS
#  build_ios:
#    name: Flutter Build IPA
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter clean
#      - run: flutter build ios