#name: CI
#on:
#  pull_request:
#  push:
#    branches:
#      - master
#
#jobs:
#
#  build_apk:
#    name: Flutter Build APK For Android
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.16.0'
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter clean
#      - run: flutter build appbundle
#
## build_ios:
##   name: Flutter Build IPA
##   runs-on: macos-latest
##   steps:
##     - uses: actions/checkout@v2
##     - uses: subosito/flutter-action@v2
##       with:
##         flutter-version: '3.16.0' # إصدار Flutter الذي يتضمن Dart SDK 3.5.4
##         channel: 'stable'
##     - run: flutter pub get
##     - run: flutter clean
##     - run: flutter build ios
